/**
 * @description ICON文件路径映射表
 */

const ICON_BASE_URL = 'https://zjyt.cqytxy.edu.cn/static/yt-ui/icons';
export const iconMap: Record<string, string> = {
  Home: `${ICON_BASE_URL}/home.png`,
  Course: `${ICON_BASE_URL}/course.png`,
  Community: `${ICON_BASE_URL}/community.png`,
  Me: `${ICON_BASE_URL}/me.png`,
  QRcode: `${ICON_BASE_URL}/QRcode.png`,
  HomeActive: `${ICON_BASE_URL}/home_active.png`,
  CourseActive: `${ICON_BASE_URL}/course_active.png`,
  CommunityActive: `${ICON_BASE_URL}/community_active.png`,
  MeActive: `${ICON_BASE_URL}/me_active.png`,
  ArrowLeft: `${ICON_BASE_URL}/arrow_left.png`,
  ArrowRight: `${ICON_BASE_URL}/arrow_right.png`,
  ArrowUp: `${ICON_BASE_URL}/arrow_up.png`,
  ArrowDown: `${ICON_BASE_URL}/arrow_down.png`,
  ArrowLeftWhite: `${ICON_BASE_URL}/arrow_left_white.png`,
  ArrowRightWhite: `${ICON_BASE_URL}/arrow_right_white.png`,
  ArrowUpWhite: `${ICON_BASE_URL}/arrow_up_white.png`,
  ArrowDownWhite: `${ICON_BASE_URL}/arrow_down_white.png`,
  Calendar: `${ICON_BASE_URL}/calendar.png`,
  DefaultAvatar: `${ICON_BASE_URL}/default_avatar.png`,
  DoorEnter: `${ICON_BASE_URL}/door_enter.png`,
  DoorExit: `${ICON_BASE_URL}/door_exit.png`,
  Edit: `${ICON_BASE_URL}/edit.png`,
  HotTopic: `${ICON_BASE_URL}/hot_topic.png`,
  Identity: `${ICON_BASE_URL}/identity.png`,
  Official: `${ICON_BASE_URL}/official.png`,
  Passed: `${ICON_BASE_URL}/passed.png`,
  Unpassed: `${ICON_BASE_URL}/unpassed.png`,
  SuccessResult: `${ICON_BASE_URL}/success_result.png`,
  FailResult: `${ICON_BASE_URL}/fail_result.png`,
  InfoResult: `${ICON_BASE_URL}/info_result.png`,
  Time: `${ICON_BASE_URL}/time.png`,
  Slider: `${ICON_BASE_URL}/slider.png`,
  Close: `${ICON_BASE_URL}/close.png`,
  Search: `${ICON_BASE_URL}/search.png`,
  Plus: `${ICON_BASE_URL}/plus.png`,
  Fail: `${ICON_BASE_URL}/fail.png`,
  Done: `${ICON_BASE_URL}/done.png`,
  Empty: `${ICON_BASE_URL}/empty.png`,
  Champion: `${ICON_BASE_URL}/champion.png`,
  Error: `${ICON_BASE_URL}/error.png`,
  FirstPlace: `${ICON_BASE_URL}/first_place.png`,
  SecondPlace: `${ICON_BASE_URL}/second_place.png`,
  ThirdPlace: `${ICON_BASE_URL}/third_place.png`,
  Winner: `${ICON_BASE_URL}/winner.png`,
  Read: `${ICON_BASE_URL}/read.png`
}
