export type BorderStyle =
  | 'none' // 无边框
  | 'solid' // 实线边框
  | 'dashed' // 虚线边框
  | 'dotted' // 点线边框
  | 'double' // 双线边框（部分平台支持）
  | 'groove' // 3D凹槽边框（部分平台支持）
  | 'ridge' // 3D脊状边框（部分平台支持）
  | 'inset' // 3D内嵌边框（部分平台支持）
  | 'outset' // 3D外凸边框（部分平台支持）
